package com.blogspot.mstachniuk.hamcrestvsfest;

import org.fest.assertions.api.AbstractAssert;


/**
 * {@link SiderealYear} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SiderealYearAssert extends AbstractAssert<SiderealYearAssert, SiderealYear> {

    /**
     * Creates a new </code>{@link SiderealYearAssert}</code> to make assertions on actual SiderealYear.
     *
     * @param actual the SiderealYear we want to make assertions on.
     */
    public SiderealYearAssert(SiderealYear actual) {
        super(actual, SiderealYearAssert.class);
    }

    /**
     * An entry point for SiderealYearAssert to follow Fest standard <code>assertThat()</code> statements.<br>
     * With a static import, one's can write directly : <code>assertThat(mySiderealYear)</code> and get specific assertion with code completion.
     *
     * @param actual the SiderealYear we want to make assertions on.
     * @return a new </code>{@link SiderealYearAssert}</code>
     */
    public static SiderealYearAssert assertThat(SiderealYear actual) {
        return new SiderealYearAssert(actual);
    }

}
